### ISSUE TITLE
NameError - uninitialized constant Sinatra::Async::Helpers::EM:

### ISSUE THREAD

**Issue by amake** [biesiad/deelay-ruby#11]
I just installed with `gem install deelay` but when trying to use it I get the following error:

```
::1 - - [26/Mar/2018:18:17:10 JST] "GET /1000/http://ipredacted:9001/path/to/my/asset HTTP/1.1" 500 133958
- -> /1000/http://ipredacted:9001/path/to/my/asset
2018-03-26 18:17:11 - NameError - uninitialized constant Sinatra::Async::Helpers::EM:
	/Users/amake/.gem/gems/async_sinatra-1.3.0/lib/sinatra/async.rb:139:in `native_async_schedule'
	/Users/amake/.gem/gems/async_sinatra-1.3.0/lib/sinatra/async.rb:131:in `async_schedule'
	/Users/amake/.gem/gems/async_sinatra-1.3.0/lib/sinatra/async.rb:149:in `async_runner'
	/Users/amake/.gem/gems/async_sinatra-1.3.0/lib/sinatra/async.rb:75:in `block in aroute'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `call'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `block in compile!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/Users/amake/.gem/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/amake/.gem/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/amake/.gem/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/amake/.gem/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/Users/amake/.gem/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/Users/amake/.gem/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/amake/.gem/gems/rack-2.0.4/lib/rack/null_logger.rb:9:in `call'
	/Users/amake/.gem/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/Users/amake/.gem/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/Users/amake/.gem/gems/rack-2.0.4/lib/rack/handler/webrick.rb:86:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

I am on macOS 10.13.3 with stock Ruby, gems installed to user with `GEM_HOME=~/.gem`.

**Comment by isole** [comment]
Same here, with macos 10.12.6 and Ruby 2.5.0

**Comment by amake** [comment]
This gem and even some of its major dependencies seem to have been abandoned years ago.

I ended up using [toxiproxy](https://github.com/Shopify/toxiproxy) instead.

**Comment by biesiad** [comment]
I build and run it with ruby 2.3.5 and it works ok. I updated the gem to be more explicit about the ruby version that it works with.
